-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 19:27:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema facturación
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `facturación` ;

-- -----------------------------------------------------
-- Schema facturación
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturación` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema bdvideojuegosmarlon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdvideojuegosmarlon` ;

-- -----------------------------------------------------
-- Schema bdvideojuegosmarlon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdvideojuegosmarlon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `facturación` ;

-- -----------------------------------------------------
-- Table `facturación`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturación`.`categoria` (
  `id_categoria` INT NOT NULL,
  `nombrecategoria` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `facturación`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturación`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(16) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `cedula` ON `facturación`.`cliente` (`cedula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `facturación`.`modo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturación`.`modo_pago` (
  `num_pago` INT NOT NULL,
  `nombreModoP` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`num_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `facturación`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturación`.`factura` (
  `num_factura` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `num_pago` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`num_factura`),
  CONSTRAINT `factura_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `facturación`.`cliente` (`id_cliente`),
  CONSTRAINT `factura_ibfk_2`
    FOREIGN KEY (`num_pago`)
    REFERENCES `facturación`.`modo_pago` (`num_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_cliente` ON `facturación`.`factura` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `num_pago` ON `facturación`.`factura` (`num_pago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `facturación`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturación`.`producto` (
  `id_producto` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `nombreProducto` VARCHAR(30) NOT NULL,
  `precio` FLOAT NOT NULL,
  `Existencia` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `facturación`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_categoria` ON `facturación`.`producto` (`id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `facturación`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturación`.`detalle` (
  `num_detalle` INT NOT NULL,
  `num_factura` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`num_detalle`),
  CONSTRAINT `detalle_ibfk_1`
    FOREIGN KEY (`num_factura`)
    REFERENCES `facturación`.`factura` (`num_factura`),
  CONSTRAINT `detalle_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `facturación`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `num_factura` ON `facturación`.`detalle` (`num_factura` ASC) VISIBLE;

CREATE INDEX `id_producto` ON `facturación`.`detalle` (`id_producto` ASC) VISIBLE;

USE `bdvideojuegosmarlon` ;

-- -----------------------------------------------------
-- Table `bdvideojuegosmarlon`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdvideojuegosmarlon`.`bitacora` (
  `id_bitacora` INT NOT NULL AUTO_INCREMENT,
  `evento` VARCHAR(255) NOT NULL,
  `fecha_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_bitacora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdvideojuegosmarlon`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdvideojuegosmarlon`.`categoria` (
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdvideojuegosmarlon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdvideojuegosmarlon`.`usuario` (
  `id_Usuario` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdvideojuegosmarlon`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdvideojuegosmarlon`.`producto` (
  `id_producto` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `nombreProducto` VARCHAR(30) NOT NULL,
  `precio` FLOAT NOT NULL,
  `Stock` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `bdvideojuegosmarlon`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_categoria` ON `bdvideojuegosmarlon`.`producto` (`id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdvideojuegosmarlon`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdvideojuegosmarlon`.`venta` (
  `id_venta` INT NOT NULL,
  `id_Usuario` INT NOT NULL,
  `nombreCliente` VARCHAR(30) NOT NULL,
  `id_producto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_venta`),
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bdvideojuegosmarlon`.`usuario` (`id_Usuario`),
  CONSTRAINT `venta_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bdvideojuegosmarlon`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_Usuario` ON `bdvideojuegosmarlon`.`venta` (`id_Usuario` ASC) VISIBLE;

CREATE INDEX `id_producto` ON `bdvideojuegosmarlon`.`venta` (`id_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdvideojuegosmarlon`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdvideojuegosmarlon`.`detalle` (
  `num_detalle` INT NOT NULL,
  `id_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`num_detalle`),
  CONSTRAINT `detalle_ibfk_1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `bdvideojuegosmarlon`.`venta` (`id_venta`),
  CONSTRAINT `detalle_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bdvideojuegosmarlon`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `num_venta` ON `bdvideojuegosmarlon`.`detalle` (`id_venta` ASC) VISIBLE;

CREATE INDEX `id_producto` ON `bdvideojuegosmarlon`.`detalle` (`id_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
